server:
  port: 8081
spring:
  data:
    redis:
      repository-type: default
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 600000
      cache-null-value: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
