services:
  datasource:
    image: mysql:8.3-oraclelinux8
    container_name: datasource
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'rabbitmq'
      MYSQL_DATABASE: 'rabbitmq'
      MYSQL_PASSWORD: 'rabbitmq'
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      interval: 10s
      retries: 10
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - rabbit-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rabbit-network
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - rabbit-network
  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    environment:
     SPRING_DATA_REDIS_HOST: redis
     SPRING_DATA_REDIS_PORT: 6379
     SPRING_RABBITMQ_HOST: rabbitmq
     SPRING_RABBITMQ_PORT: 5672
     SPRING_RABBITMQ_USERNAME: guest
     SPRING_RABBITMQ_PASSWORD: guest
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8081:8081"
    restart: on-failure
    networks:
      - rabbit-network
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      datasource:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://datasource:3306/rabbit
      SPRING_DATASOURCE_USERNAME: rabbitmq
      SPRING_DATASOURCE_PASSWORD: rabbitmq
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
    restart: on-failure
    networks:
      - rabbit-network
volumes:
  my-db:
  rabbitmq-data:
  redis_data:
networks:
  rabbit-network:
    driver: bridge