services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
  publisher:
    build:
      context: ./publisher
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8081:8081"
    restart: on-failure
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    restart: on-failure
volumes:
  rabbitmq-data: