server:
  port: 8080
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  datasource:
    url: jdbc:mysql://datasource:3306/rabbitmq
    username: rabbitmq
    password: rabbitmq
    driver-class-name: com.mysql.cj.jdbc.Driver
    flyway:
      enabled: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true