apiVersion: v1
kind: Service
metadata:
  name: consumer
  namespace: consumer-app
spec:
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer