apiVersion: v1
kind: Service
metadata:
  name: publisher
  namespace: publisher-app
spec:
  selector:
    app: publisher
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer